aws_region                      = "us-east-1"
env                             = "main"
s3_bucket                       = "lambdas-artifacts-main"
source_code_hash_auth_login     = ""
source_code_hash_auth_register  = ""
