name: Build and Upload Lambda

on:
  push:
    branches:
      - main
      - stage

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Lambda with esbuild
        run: |
          npx esbuild src/handler.ts \
            --bundle \
            --platform=node \
            --target=node20 \
            --outfile=dist/index.js

      - name: Zip function
        run: zip -j function.zip dist/index.js

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: |
          BRANCH=$(echo "${GITHUB_REF##*/}")
          aws s3 cp function.zip s3://lambdas-artifacts-$BRANCH/auth-service/$BRANCH/function.zip
